### ISSUE TITLE
`Error: Cannot find module '@samchon/openapi/lib/composers/LlmSchemaComposer'` after updating to 7.4.1

### ISSUE THREAD

**Issue by MathiasWP** [samchon/typia#1441]
### 📝 Summary
  - **Typia Version**: 7.4.1
  - **Expected behavior**: Build should complete
  - **Actual behavior**: Building fails

I'm running the following script to build my project `ts-patch install && typia patch && typia generate --input src --output typia`. This worked fine on the latest version 6, but after upgrading to version 7.4.1 i get the following error output in my terminal:

```
Error: Cannot find module '@samchon/openapi/lib/composers/LlmSchemaComposer'
Require stack:
- /app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/programmers/llm/LlmApplicationProgrammer.js
- /app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/programmers/llm/LlmApplicationOfValidateProgrammer.js
- /app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/transformers/features/llm/LlmApplicationOfValidateTransformer.js
- /app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/transformers/CallExpressionTransformer.js
- /app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/transformers/NodeTransformer.js
- /app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/transformers/FileTransformer.js
- /app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/transform.js
- /app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/programmers/TypiaProgrammer.js
- /app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/executable/TypiaGenerateWizard.js
- /app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/executable/typia.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/programmers/llm/LlmApplicationProgrammer.js:4:29)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/programmers/llm/LlmApplicationProgrammer.js', 'app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/programmers/llm/LlmApplicationOfValidateProgrammer.js', 'app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/transformers/features/llm/LlmApplicationOfValidateTransformer.js', 'app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/transformers/CallExpressionTransformer.js', 'app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/transformers/NodeTransformer.js', 'app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/transformers/FileTransformer.js', 'app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/transform.js',
'app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/programmers/TypiaProgrammer.js', 'app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/executable/TypiaGenerateWizard.js', 'app/node_modules/.pnpm/typia@7.4.1_@samchon+openapi@1.2.2_typescript@5.6.3/node_modules/typia/lib/executable/typia.js'
  ]
}
```

Here's an example of how Typia is used throughout the codebase. All occurrences of Typia is used like this:

```ts
import { Filesystem } from "@backend/contracts";
import typia from "typia";
import { Endpoint } from "../../../Core/Endpoint/Endpoint";

type Input = {
    path?: string;
    namespace?: {
        id?: string;
        name?: string;
    };
    name: string;
    directory?: string;
};

type Output = {};

export default class CreateDirectoryEndpoint extends Endpoint<Input, Output> {
    validator = typia.createValidateEquals<Input>();

    protected override async performCall(input: Input): Promise<Output> {
        return await this.commandBus.run<Output>(
            new Filesystem.CreateDirectoryCommand(
                input.name,
                input.directory,
                input.namespace,
                input.path
            )
        );
    }
}
```

It's a NodeJS project in CommonJS using TypeScript version ^5.6.2.

**Comment by samchon** [comment]
Well, `typia` has peer dependency to the `@samchon/openapi` v2.

Would you set it up again?

**Comment by MathiasWP** [comment]
> Well, `typia` has peer dependency to the `@samchon/openapi` v2.
> 
> Would you set it up again?

Meaning that i have to install @samchon/openapi manually?

**Comment by samchon** [comment]
No, run pnpm install command again or clean install the pnpm.

**Comment by samchon** [comment]
Also, do not forget re-compilation.

**Comment by MathiasWP** [comment]
that did the trick! thanks
